### ISSUE TITLE
flag error

### ISSUE THREAD

**Issue by ghost** [luispedro/mergedirs#1]
I got this error when trying to run 
`python merge.py` 

> File "merge.py", line 4, in <module>
>     from .flags import set_oldest
> SystemError: Parent module '' not loaded, cannot perform relative import

It seems to be fixed when I change `.flags` to `flags` in merge.py

**Comment by luispedro** [comment]
Closing as likely out of date. `mergedirs` is now a proper Python package that you install with `python setup.py install`
